#version 450

layout(local_size_x = 16) in;


struct Frustum {
  vec4 planes[6];  // near, far, left, right, top, bottom
};

layout(push_constant) uniform params_t
{
  Frustum camera_frustum;
  uint instances_count;
} params;

layout(binding = 0) readonly buffer DrawParams
{
  mat4 mModel[];
} drawParams;

struct AABB
{
  vec4 min;
  vec4 max;
};

layout(binding = 1) readonly buffer AABBs
{
  AABB boxes[];
} aabbs;


struct IndirectDrawCommand {
  uint    indexCount;
  uint    instanceCount;
  uint    firstIndex;
  int     vertexOffset;
  uint    firstInstance;
};

layout(binding = 2) buffer Commands {
  IndirectDrawCommand commands[];
} commands;

layout(binding = 3) writeonly buffer DrawParamsIndices {
  uint indices[];
} drawParamsIndices;

layout(binding = 4) readonly buffer CommandIndices {
  uint commandIndices[];
} commandIndices;


bool isInFront(vec3 point, vec4 plane) {
  float a = dot(plane.xyz, point);
  return a >= plane.w;
}

bool IntersectsFrustum(AABB aabb) {
  uint gID = gl_GlobalInvocationID.x;
  for (int plane_i = 0; plane_i < 6; ++plane_i) {
    bool have_in_front = false;

    for (int x = 0; x < 2; ++x) {
      for (int y = 0; y < 2; ++y) {
        for (int z = 0; z < 2; ++z) {
          vec3 choice = vec3(x, y, z);
          vec3 point = mix(aabb.min.xyz, aabb.max.xyz, choice);
          vec4 transformed = drawParams.mModel[gID] * vec4(point, 1.0f);
          transformed /= transformed.w;

          if (isInFront(transformed.xyz, params.camera_frustum.planes[plane_i])) {
            have_in_front = true;
          }
        }
      }
    }

    if (!have_in_front) {
      return false;
    }
  }

  return true;
}

void main(void)
{
  uint gID = gl_GlobalInvocationID.x;
  if (gID >= params.instances_count) {
    return;
  }

  // Command indices are also relem indices.
  uint command_index = commandIndices.commandIndices[gID];
  AABB aabb = aabbs.boxes[command_index];

  commands.commands[command_index].instanceCount = 0;
  barrier();

  if (IntersectsFrustum(aabb)) {
    uint index = atomicAdd(commands.commands[command_index].instanceCount, 1);
    uint offset = commands.commands[command_index].firstInstance;
    drawParamsIndices.indices[offset + index] = gID;
  }
}
